version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    ## https://stackoverflow.com/questions/35832095/difference-between-links-and-depends-on-in-docker-compose-yml
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      ## for running interactively, localhost is used. but the Docker image needs something other than localhost
      - POSTGRES_HOST=db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
