name: backend
on:
  push:
    branches:
      - master
    paths:
      - backend/**
      - .github/**
  pull_request:
    branches:
      - master
    paths:
      - backend/**
      - .github/**
  workflow_dispatch:
jobs:
  black:
    uses: ./.github/workflows/reusable-poetry-setup.yml
    with:
      customName: 'Black'
      customCommand: 'black . --check --verbose --diff --color'
  mypy:
    uses: ./.github/workflows/reusable-poetry-setup.yml
    with:
      customName: 'MyPy'
      customCommand: 'mypy .'
